version: "3.9"
services:
  auto:
    build:
      context: ../
      dockerfile: Dockerfile
    # env_file: .env
    tty: true
    stdin_open: true
    # ports:
    #   - 8099:8099
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
